apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  test: test123
  name: {{ .Files.Get "files/new.txt" }}
  index: "{{ index .Files "files/new.txt" | toString  | repeat 5 }}"
  bytes: "{{ .Files.GetBytes "files/new.txt" }}"
  template_name: {{ .Template.Name }}
  template_path: {{ .Template.BasePath }}
  number: {{ quote .Values.number }}
  number1: {{ .Values.number | quote }}
  number2: "{{ .Values.number }}"
  equal: {{ eq .Values.x1 .Values.x2 }}


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-1
data:
{{- if eq .Values.drink "coffee" }}
  mug: "true"
{{ end -}}
  {{- if eq .Values.drink "coffee" }}
  mug1: "true"
  {{ end -}}
  myvalue: "Hello World"

