apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  test: test123
  name: {{ .Files.Get "files/new.txt" }}
  index: "{{ index .Files "files/new.txt" | toString }}"
  bytes: "{{ .Files.GetBytes "files/new.txt" }}"
  template_name: {{ .Template.Name }}
  template_path: {{ .Template.BasePath }}




